# Домашнее задание к лекции "Функции"



Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1.    перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```

2.    перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:

*    код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
*    в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
*    пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").



In [1]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

#### **Примечание**
*Для решения поставленной задачи, вначале были написаны функции к каждому заданию и пункту, которые впоследствии были объединены в одну - main().*


---



## Задание 1

### Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру

Примеры работы:
1. 
> Введите команду:
p

> Введите номер документа:
10006

Результат:
```Владелец документа: Аристарх Павлов```

2. 
> Введите команду:
p

> Введите номер документа:
12345

Результат:
```Документ не найден в базе```

In [2]:
def doc_owner ():
    """
    Пользователь может узнать владельца документа по его номеру
    """
    number = input('Введите номер документа: ')
    for i in documents:
        if i['number'] == number:
            result = i['name']
            break
        else:
            result = 'Документ не найден в базе'
    print(result)

In [3]:
doc_owner()

Введите номер документа: 11-2
Геннадий Покемонов


In [4]:
doc_owner()

Введите номер документа: 10006
Аристарх Павлов


### Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится

Примеры работы:
1. 
> Введите команду:
s

> Введите номер документа:
10006

Результат:
```Документ хранится на полке: 2```

2. 
> Введите команду:
s

> Введите номер документа:
12345

Результат:
```Документ не найден в базе```

In [5]:
def doc_loc ():
    """
    Пользователь может по номеру документа узнать на какой полке он хранится
    """
    number = input('Введите номер документа: ')
    for k, v in directories.items():
      if number in v:
        result = 'Документ хранится на полке: ' + k
        break
      else:
        result = 'Документ не найден в базе'
    print(result)

In [6]:
doc_loc()

Введите номер документа: 2207 876234
Документ хранится на полке: 1


In [7]:
doc_loc()

Введите номер документа: 10006
Документ хранится на полке: 2


### Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам

Пример работы:

> Введите команду:
l

Результат:
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [8]:
def doc_info ():
    """
    Пользователь может увидеть полную информацию по всем документам
    """
    for doc in documents:
        number_doc = doc['number']
        type_doc = doc['type']
        owner_doc = doc['name']
        for i in directories:
            for v in directories[i]:
                if number_doc in v:
                    direct_doc = i
        print(f'№:  {number_doc}, тип: {type_doc}, владелец: {owner_doc}, полка хранения: {direct_doc}')

In [9]:
doc_info()

№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Пункт 4. Пользователь по команде "ads" может добавить новую полку

Примеры работы:
1. 
> Введите команду:
ads

> Введите номер полки:
10

Результат:
```Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.```

2. 
> Введите команду:
ads

> Введите номер полки:
1

Результат:
```Такая полка уже существует. Текущий перечень полок: 1, 2, 3.```

In [10]:
def ads_loc ():
    number_loc = input('Введите номер полки: ')
    if number_loc in directories.keys():
        print(f'Такая полка уже существует. Текущий перечень полок: {",".join(list(directories.keys()))}')
    else:
        directories[number_loc] = []
        print(f'Полка добавлена. Текущий перечень полок: {",".join(list(directories.keys()))}')

In [11]:
ads_loc()

Введите номер полки: 1
Такая полка уже существует. Текущий перечень полок: 1,2,3


In [12]:
ads_loc()

Введите номер полки: 4
Полка добавлена. Текущий перечень полок: 1,2,3,4


### Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)

Примеры работы:
1. 
> Введите команду:
ds

> Введите номер полки:
3

Результат:
```Полка удалена. Текущий перечень полок: 1, 2.```

2. 
> Введите команду:
ds

> Введите номер полки:
1

Результат:
```На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.```

3. 
> Введите команду:
ds

> Введите номер полки:
4

Результат:
```Такой полки не существует. Текущий перечень полок: 1, 2, 3.```

In [13]:
def del_loc ():
    number_loc = input('Введите номер полки: ')
    if number_loc not in directories.keys():
        print(f'Такой полки не существует. Текущий перечень полок: {",".join(list(directories.keys()))}')
    elif number_loc in directories.keys() and directories[number_loc] == []:
        del(directories[number_loc])
        print(f'Полка удалена. Текущий перечень полок: {",".join(list(directories.keys()))}')
    else:
        print(f'На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: {",".join(list(directories.keys()))}')

In [14]:
del_loc()

Введите номер полки: 9
Такой полки не существует. Текущий перечень полок: 1,2,3,4


In [15]:
del_loc()

Введите номер полки: 4
Полка удалена. Текущий перечень полок: 1,2,3


In [16]:
#Итоговая версия  обязательной части задания
def main ():
   """
    Пользователь по команде "p" может узнать владельца документа по его номеру
    Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
    Пользователь по команде "l" может увидеть полную информацию по всем документам
    Пользователь по команде "ads" может добавить новую полку
    Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
    Пользователь по команде "q" останавливает программу
    """
command = input('Введите команду: ')
while command != 'q':
  if command == 'p':
    doc_owner()
    command = input('Введите команду: ')
  elif command == 's':
    doc_loc()
    command = input('Введите команду: ')
  elif command == 'l':
    doc_info()
    command = input('Введите команду: ')
  elif command == 'ads':
    ads_loc()
    command = input('Введите команду: ')
  elif command == 'ds':
    del_loc()
    command = input('Введите команду: ')
  else:
    print('Ошибка. Некорректная команда.')
    command = input('Введите команду: ')

Введите команду: p
Введите номер документа: 11-2
Геннадий Покемонов
Введите команду: l
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду: ads
Введите номер полки: 4
Полка добавлена. Текущий перечень полок: 1,2,3,4
Введите команду: q


## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "ad" может добавить новый документ в данные

Примеры работы:
1. 
> Введите команду:
ad

> Введите номер документа:
42

> Введите тип документа:
multipassport

> Введите владельца документа:
R2D2

>Введите полку для хранения:
3

Результат:
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```
2. 
> Введите команду:
ad

> Введите номер документа:
42

> Введите тип документа:
multipassport

> Введите владельца документа:
R2D2

> Введите полку для хранения:
4

Результат:
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [17]:
def doc_add ():
    """
    Пользователь по команде "ad" может добавить новый документ в данные
    """
    doc_num = input('Введите номер документа: ')
    doc_type = input('Введите тип документа: ')
    doc_owner = input('Введите владельца документа: ')
    doc_loc = input('Введите полку для хранения: ')
    if doc_loc not in directories.keys():
        print(f'Такой полки не существует. Добавьте полку командой ads. \nТекущий список документов: ')
        doc_info()
    else:
        documents.append({'type': doc_type, 'number': doc_num, 'name': doc_owner})
        directories[doc_loc].append(doc_num)
        print(f'Документ добавлен. Текущий список документов: ')
        doc_info()

In [18]:
doc_add()

Введите номер документа: 42
Введите тип документа: multipassport
Введите владельца документа: R2D2
Введите полку для хранения: 5
Такой полки не существует. Добавьте полку командой ads. 
Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [19]:
doc_add()

Введите номер документа: 42
Введите тип документа: multipassport
Введите владельца документа: R2D2
Введите полку для хранения: 3
Документ добавлен. Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№:  42, тип: multipassport, владелец: R2D2, полка хранения: 3


### Пункт 2. Пользователь по команде "d" может удалить документ из данных

Примеры работы:
1. 
> Введите команду:
d

> Введите номер документа:
10006

Результат:
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```
2. 
> Введите команду:
d

> Введите номер документа:
123456

Результат:
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [20]:
def del_doc ():
  """
  Пользователь может удалить документ из данных
  """
  doc_num = input('Введите номер документа: ')
  for i in documents:
      if doc_num == i['number']:
        documents.remove(i)
        for i in directories:
          for v in directories[i]:
            if doc_num in v:
              direct_doc = i
        directories[direct_doc].remove(doc_num)
        text_del = 'Документ удален. \nТекущий список документов: '
      else:
        text_del = 'Документ не найден в базе. \nТекущий список документов:'
  print(text_del)
  doc_info()

In [21]:
del_doc()

Введите номер документа: vghsbcdzljvn
Документ не найден в базе. 
Текущий список документов:
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№:  42, тип: multipassport, владелец: R2D2, полка хранения: 3


In [22]:
del_doc()

Введите номер документа: 42
Документ удален. 
Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Пункт 3. Пользователь по команде "m" может переместить документ с полки на полку

Примеры работы:
1. 
> Введите команду:
m

> Введите номер документа:
11-2

> Введите номер полки:
3

Результат:
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```
2. 
> Введите команду:
m

> Введите номер документа:
11-2

> Введите номер полки:
10

Результат:
```Такой полки не существует. Текущий перечень полок: 1, 2, 3.```

3. 
> Введите команду:
m

> Введите номер документа:
42

> Введите номер полки:
2

Результат:
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [23]:
def doc_reloc ():
  """
  Пользователь может переместить документ с полки на полку
  """
  doc_num = input('Введите номер документа: ')
  doc_new_loc = input('Введите номер полки: ')
  if doc_new_loc not in directories.keys():
    print(f'Такой полки не существует.  \nТекущий список полок: {",".join(list(directories.keys()))}')
  else:
    for i in documents:
      if doc_num == i['number']:
        for i in directories:
          for v in directories[i]:
            if doc_num in v:
              direct_doc = i
        directories[direct_doc].remove(doc_num)
        directories[doc_new_loc].append(doc_num)
        text_reloc = 'Документ перемещен. \nТекущий список документов: '
        break
      else:
        text_reloc = 'Документ не найден в базе. \nТекущий список документов: '
    print(text_reloc)
    doc_info()

In [24]:
doc_reloc()

Введите номер документа: 11-2
Введите номер полки: 9
Такой полки не существует.  
Текущий список полок: 1,2,3,4


In [25]:
doc_reloc()

Введите номер документа: 11-2
Введите номер полки: 3
Документ перемещен. 
Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [26]:
doc_reloc()

Введите номер документа: lsdv,;l5
Введите номер полки: 1
Документ не найден в базе. 
Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [27]:
#Полная итоговая версия 
def main ():
   """
    Пользователь по команде "p" может узнать владельца документа по его номеру
    Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
    Пользователь по команде "l" может увидеть полную информацию по всем документам
    Пользователь по команде "ads" может добавить новую полку
    Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
    Пользователь по команде "ad" может добавить новый документ в данные
    Пользователь по команде "d" может удалить документ из данных
    Пользователь по команде "m" может переместить документ с полки на полку
    Пользователь по команде "q" останавливает программу
    """
command = input('Введите команду: ')
while command != 'q':
  if command == 'p':
    doc_owner()
    command = input('Введите команду: ')
  elif command == 's':
    doc_loc()
    command = input('Введите команду: ')
  elif command == 'l':
    doc_info()
    command = input('Введите команду: ')
  elif command == 'ads':
    ads_loc()
    command = input('Введите команду: ')
  elif command == 'ds':
    del_loc()
    command = input('Введите команду: ')
  elif command == 'ad':
      doc_add()
      command = input('Введите команду: ')
  elif command == 'd':
      del_doc()
      command = input('Введите команду: ')
  elif command == 'm':
      doc_reloc()
      command = input('Введите команду: ')
  else:
      print('Ошибка. Некорректная команда')
      command = input('Введите команду: ')

Введите команду: p
Введите номер документа: 10006
Аристарх Павлов
Введите команду: ds
Введите номер полки: 2
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1,2,3,4
Введите команду: m
Введите номер документа: 10006
Введите номер полки: 3
Документ перемещен. 
Текущий список документов: 
№:  2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№:  11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№:  10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
Введите команду: q
